"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Calendar, Users, Wallet, Clock, MapPin, Check, ArrowDown, Sparkles, CheckCircle2, XCircle, Pencil } from "lucide-react";
import { useSavePlan, useUpdateTrip } from "@/lib/queries";
import type { TripPlan } from "@/types";

const FIT_STYLES: Record<string, string> = {
  hemat: "bg-green-50 text-green-700",
  pas: "bg-blue-50 text-blue-700",
  over: "bg-red-50 text-red-700",
  estimasi: "bg-gray-100 text-gray-600",
};
const FIT_LABEL: Record<string, string> = {
  hemat: "Hemat", pas: "Pas", over: "Over budget", estimasi: "Estimasi",
};
const rupiah = (n: number) => "Rp" + Math.round(n || 0).toLocaleString("id-ID");

const BAR_COLORS: Record<string, string> = {
  activities: "bg-blue-500",
  accommodation: "bg-indigo-500",
  transport: "bg-cyan-400",
};

export function PlanCard({ plan, onEdit, onCancel: onCancelPlan }: { plan: TripPlan; onEdit?: () => void; onCancel?: () => void }) {
  const router = useRouter();
  const save = useSavePlan();
  const updateTrip = useUpdateTrip();
  const [savedId, setSavedId] = useState<string | null>(null);
  const [state, setState] = useState<"idle" | "saving" | "approved">("idle");
  const be = plan.budget_estimate;
  const total = be.total || 1;

  const onApprove = async () => {
    if (state === "approved") return;
    setState("saving");
    const id = await save.mutateAsync(plan);
    // Mark as planned so it shows in trip history.
    await updateTrip.mutateAsync({ tripId: id, data: { status: "planned" } });
    setSavedId(id);
    setState("approved");
  };

  const onCancel = () => {
    // Discard plan — no trip is created. Stay in chat to refine or ask again.
    setState("idle");
    onCancelPlan?.();
  };

  return (
    <div className="mt-2 w-full rounded-2xl border border-gray-200 bg-white overflow-hidden text-left">
      {/* header */}
      <div className="relative p-3 bg-gradient-to-r from-primary to-secondary text-white">
        <p className="text-sm font-bold leading-snug">{plan.title}</p>
        <div className="flex flex-wrap items-center gap-x-3 gap-y-0.5 mt-1 text-[11px] text-white/80">
          <span className="flex items-center"><Calendar className="w-3 h-3 mr-1" />{plan.num_days} hari</span>
          <span className="flex items-center"><Users className="w-3 h-3 mr-1" />{plan.people} orang</span>
          {plan.location && (
            <span className="flex items-center"><MapPin className="w-3 h-3 mr-1" />{plan.location}</span>
          )}
        </div>
        <div className="absolute top-2 right-2 bg-white/20 backdrop-blur-sm px-2 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-wider text-white flex items-center gap-1">
          <Sparkles className="w-3 h-3" /> Generated by Poca
        </div>
      </div>

      {/* budget */}
      <div className="p-3 border-b border-gray-100">
        <div className="flex items-center justify-between">
          <span className="text-[11px] text-gray-500 flex items-center">
            <Wallet className="w-3 h-3 mr-1" />Total perkiraan
          </span>
          <span className="text-sm font-bold text-gray-900">{rupiah(be.total)}</span>
        </div>
        <div className="flex items-center justify-between mt-1">
          <span className="text-[10px] text-gray-400">{be.per_day ? `~${rupiah(be.per_day)}/hari` : ""}</span>
          <span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold ${FIT_STYLES[plan.budget_fit] || FIT_STYLES.estimasi}`}>
            {FIT_LABEL[plan.budget_fit] || plan.budget_fit}
            {plan.budget_delta != null && plan.budget_fit !== "estimasi" &&
              ` · ${plan.budget_delta >= 0 ? "+" : ""}${rupiah(plan.budget_delta)}`}
          </span>
        </div>
        {/* breakdown bar */}
        <div className="mt-2 flex h-1.5 rounded-full overflow-hidden bg-gray-100">
          {["activities", "accommodation", "transport"].map((k) =>
            be.breakdown?.[k] ? (
              <div
                key={k}
                className={BAR_COLORS[k] || "bg-gray-400"}
                style={{ width: `${(be.breakdown[k] / total) * 100}%` }}
                title={`${k}: ${rupiah(be.breakdown[k])}`}
              />
            ) : null,
          )}
        </div>
      </div>

      {/* days */}
      <div className="divide-y divide-gray-100">
        {plan.days.map((day) => (
          <div key={day.day} className="p-3">
            <p className="text-xs font-semibold text-gray-800 mb-2">
              {day.title}
              <span className="text-gray-400 font-normal"> · {day.activities.length} kegiatan</span>
            </p>
            <div className="space-y-0 relative pl-2">
              <div className="absolute left-[13px] top-2 bottom-2 w-px bg-gray-200" />
              {day.activities.map((a, i) => (
                <div key={i} className="relative pl-6 pb-4">
                  <div className="absolute left-[-3px] top-1.5 w-2 h-2 rounded-full bg-blue-500 ring-4 ring-white" />
                  <div
                    className={`flex flex-col sm:flex-row sm:items-start gap-1 sm:gap-3 ${a.destination_id ? "cursor-pointer group hover:bg-gray-50 rounded-xl p-2 -mx-2 transition-colors" : "p-2 -mx-2"}`}
                    onClick={a.destination_id ? () => router.push(`/destination/${a.destination_id}`) : undefined}
                  >
                    <span className="text-[11px] font-mono font-medium text-blue-600 bg-blue-50/80 rounded-md px-2 py-0.5 self-start flex-shrink-0 mt-0.5">
                      {a.time}
                    </span>
                    <div className="min-w-0 flex-1">
                      <p className="text-sm font-medium text-gray-900 group-hover:text-blue-700 transition-colors">
                        {a.name}
                        {a.destination_id && <MapPin className="inline w-3 h-3 ml-1 text-gray-300 group-hover:text-blue-400" />}
                      </p>
                      <p className="text-[11px] text-gray-500 mt-0.5 capitalize flex items-center">
                        {a.category}{a.location_name ? <><span className="mx-1">·</span>{a.location_name}</> : ""}
                      </p>
                    </div>
                    <span className="text-[11px] font-medium text-gray-600 bg-gray-100/80 px-2 py-1 rounded-lg self-start flex-shrink-0 mt-1 sm:mt-0">
                      {a.cost ? rupiah(a.cost) : "Gratis"}
                    </span>
                  </div>
                  {a.travel_next && (
                    <div className="flex items-center gap-1.5 py-1 text-[11px] text-gray-400 mt-1">
                      <ArrowDown className="w-3 h-3 text-gray-300" />
                      ~{a.travel_next.minutes} mnt ({a.travel_next.distance_km} km)
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* actions: approve / edit / cancel */}
      <div className="p-3 border-t border-gray-100">
        {state === "approved" ? (
          <div className="flex flex-col gap-2">
            <button
              onClick={() => router.push(`/trips/${savedId}`)}
              className="w-full flex items-center justify-center gap-1 py-2 rounded-xl bg-green-50 text-green-700 text-xs font-semibold hover:bg-green-100 transition-colors"
            >
              <CheckCircle2 className="w-3.5 h-3.5" /> Disetujui · Lihat di Trip Saya
            </button>
          </div>
        ) : (
          <div className="grid grid-cols-3 gap-2">
            <button
              onClick={onApprove}
              disabled={state === "saving"}
              className="flex flex-col items-center justify-center gap-1 py-2.5 rounded-xl bg-blue-600 text-white text-[11px] font-bold hover:bg-blue-700 disabled:opacity-50 transition-colors"
            >
              {state === "saving" ? <><Clock className="w-4 h-4 animate-spin" /> Menyimpan...</> : <><Check className="w-4 h-4" /> Setujui</>}
            </button>
            <button
              onClick={onEdit}
              className="flex flex-col items-center justify-center gap-1 py-2.5 rounded-xl bg-amber-50 text-amber-700 text-[11px] font-bold hover:bg-amber-100 transition-colors"
              title="Ubah rencana — AI akan menanyakan perubahannya"
            >
              <Pencil className="w-4 h-4" /> Edit
            </button>
            <button
              onClick={onCancel}
              className="flex flex-col items-center justify-center gap-1 py-2.5 rounded-xl bg-red-50 text-red-600 text-[11px] font-bold hover:bg-red-100 transition-colors"
            >
              <XCircle className="w-4 h-4" /> Cancel
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
