"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Bell, Bot, UserPlus, Heart, Calendar, MessageSquare, Search, Settings, Sparkles, Plane } from "lucide-react";

const NOTIFICATIONS = [
  {
    type: "ai",
    icon: Bot,
    bg: "bg-secondary-container",
    label: "GENERATED BY POCA",
    title: "Your Kyoto Autumn Escape is ready!",
    desc: "We've synthesized 14 personalized recommendations including a hidden tea house in Arashiyama.",
    time: "2m ago",
    action: "View Itinerary",
    hasBorder: true,
  },
  {
    type: "follow",
    icon: UserPlus,
    bg: "bg-primary/10",
    label: null,
    title: null,
    desc: (
      <>
        <span className="font-bold text-on-surface">Sarah Jenkins</span> started following your travel boards.
      </>
    ),
    time: "45m ago",
    action: "Follow Back",
    hasBorder: false,
  },
  {
    type: "like",
    icon: Heart,
    bg: "bg-primary/10",
    label: null,
    title: null,
    desc: (
      <>
        <span className="font-bold text-on-surface">Alex Rivera</span> and <span className="font-bold text-on-surface">12 others</span> liked your post: "Sunset over Santorini".
      </>
    ),
    time: "2h ago",
    action: null,
    hasBorder: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIszRxCQn0fPkpZizqN16VYNJqKjJ2c4yQum46PAptqemu-DbZxZWIzVfqHS2XKRCm_ddNua2uL-Q0JUxsC-A-3R1kURPv_329w1zaRffuBPLdp5d-YNI8Ly5DhVxM4QOcwb-bSL7UehL8-VqWrsDxFiE3oV2mL6TPZINbwYhclcCTnnM0lrJtum4UzRXLdvuJP3tS3SeCx2kqLAtPtIjGq3ba31hGEwcrsyBTv-bFTP7Mz0EfqYCC",
  },
  {
    type: "flight",
    icon: Calendar,
    bg: "bg-primary",
    label: null,
    title: "Flight Check-in: BA2490",
    desc: "Your flight to London Heathrow departs in 24 hours. Check-in is now open.",
    time: "5h ago",
    action: "Check-in Now",
    hasBorder: false,
    flightInfo: { from: "NYC", fromCode: "JFK", to: "LON", toCode: "LHR" },
  },
];

const EARLIER = [
  {
    icon: MessageSquare,
    bg: "bg-surface-container-high",
    desc: (
      <>
        Your review for <span className="font-bold text-on-surface">The Alchemist Cafe</span> has reached 50 helpful votes.
      </>
    ),
    time: "3d ago",
  },
];

export default function NotificationsPage() {
  const router = useRouter();
  const [allRead, setAllRead] = useState(false);

  const routeFor = (type: string) =>
    ({ ai: "/chat", follow: "/feed", like: "/feed", flight: "/trips" } as Record<string, string>)[type] || "/notifications";

  return (
    <div className="pt-16 bg-background text-on-surface min-h-screen">
      <div className="max-w-4xl mx-auto px-4 py-6">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-[36px] font-bold text-on-surface">Notifications</h1>
          <button
            onClick={() => setAllRead(true)}
            className="text-primary font-bold text-[14px] hover:underline active:scale-95 transition-all"
          >
            Mark all as read
          </button>
        </div>

        {/* Notification List */}
        <div className="space-y-4 relative">
          {NOTIFICATIONS.map((n, i) => (
            <div
              key={i}
              onClick={() => router.push(routeFor(n.type))}
              className={`${n.hasBorder ? "" : "bg-surface-container-lowest border border-outline-variant/30"} p-4 rounded-xl shadow-sm transition-all cursor-pointer ${allRead ? "opacity-70" : ""} hover:-translate-y-0.5 hover:shadow-md`}
              style={n.hasBorder ? { background: "#ffffff", border: "1px solid transparent", backgroundClip: "padding-box", position: "relative" } : {}}
            >
              {n.hasBorder && (
                <div
                  style={{
                    position: "absolute", top: 0, right: 0, bottom: 0, left: 0,
                    zIndex: -1, margin: -1, borderRadius: "inherit",
                    background: "linear-gradient(to right, #004ac6, #712ae2)",
                  }}
                />
              )}
              <div className="flex gap-4 relative z-10">
                <div className="relative">
                  <div className={`w-12 h-12 rounded-full ${n.bg} flex items-center justify-center text-on-primary shrink-0`}>
                    <n.icon className="w-5 h-5 fill-current" />
                  </div>
                  {i < NOTIFICATIONS.length - 1 && (
                    <div className="thread-line-notif" />
                  )}
                </div>
                <div className="flex-grow min-w-0">
                  <div className="flex justify-between items-start">
                    <div className="min-w-0">
                      {n.label && (
                        <span className="bg-secondary-container/10 text-secondary px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider inline-block mb-1">
                          {n.label}
                        </span>
                      )}
                      {n.title && <h3 className="text-[20px] font-semibold text-on-surface">{n.title}</h3>}
                      <p className="text-on-surface-variant text-[14px] mt-1">{n.desc}</p>

                      {/* Flight info */}
                      {n.flightInfo && (
                        <div className="mt-3 p-3 bg-surface-container-low rounded-lg border border-outline-variant/20 flex items-center justify-between">
                          <div className="flex items-center gap-3">
                            <div className="text-center px-2">
                              <span className="block font-bold text-[20px]">{n.flightInfo.from}</span>
                              <span className="text-[10px] text-outline font-bold">{n.flightInfo.fromCode}</span>
                            </div>
                            <Plane className="w-4 h-4 text-outline rotate-90" />
                            <div className="text-center px-2">
                              <span className="block font-bold text-[20px]">{n.flightInfo.to}</span>
                              <span className="text-[10px] text-outline font-bold">{n.flightInfo.toCode}</span>
                            </div>
                          </div>
                          <button className="bg-primary text-on-primary px-4 py-2 rounded-lg font-bold text-[12px]">{n.action}</button>
                        </div>
                      )}

                      {/* Like post thumbnail */}
                      {n.image && (
                        <div className="mt-3 w-24 h-16 rounded-lg overflow-hidden border border-outline-variant">
                          <img className="w-full h-full object-cover" src={n.image} alt="" />
                        </div>
                      )}

                      {/* Action button */}
                      {n.action && !n.flightInfo && (
                        <div className="mt-3 flex gap-2">
                          <button className="bg-primary text-on-primary px-4 py-2 rounded-lg font-bold text-[12px] hover:brightness-110 active:scale-95 transition-all">{n.action}</button>
                          <button className="border border-outline-variant px-4 py-2 rounded-lg font-bold text-[12px] hover:bg-surface-container-low active:scale-95 transition-all">Share</button>
                        </div>
                      )}

                      {/* Follow back */}
                      {n.action === "Follow Back" && (
                        <div className="mt-2">
                          <button className="text-primary font-bold text-[12px] hover:underline">{n.action}</button>
                        </div>
                      )}
                    </div>
                    <span className="text-[10px] text-outline font-medium flex-shrink-0">{n.time}</span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Earlier This Week */}
        <div className="pt-6 pb-3">
          <h2 className="font-bold text-[12px] text-on-surface-variant uppercase tracking-wider">Earlier This Week</h2>
        </div>
        <div className="space-y-3">
          {EARLIER.map((e, i) => (
            <div key={i} className="bg-surface-container-lowest/60 p-4 rounded-xl border border-outline-variant/20 shadow-sm transition-all cursor-pointer opacity-80 hover:opacity-100">
              <div className="flex gap-4">
                <div className={`w-12 h-12 rounded-full ${e.bg} flex items-center justify-center text-on-surface-variant shrink-0`}>
                  <e.icon className="w-5 h-5" />
                </div>
                <div className="flex-grow">
                  <div className="flex justify-between items-start">
                    <p className="text-[14px]">{e.desc}</p>
                    <span className="text-[10px] text-outline font-medium flex-shrink-0">{e.time}</span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
